### ISSUE TITLE
Questions about Manually-aligned Modelnet40

### ISSUE THREAD

**Issue by xiangchong1** [lmb-freiburg/orion#1]
Hi, thanks for your work. I have some questions about the Manually-aligned Modelnet40 you provided.
1. Is the data in .off file the aligned object? or it is the same thing as official modelnet40 data and we need to rotate the objects using the  .annot file?
2. Can you provide more information about how to use the .annot file? There are two lines in the .annot file. The first line is the rotation angle around z aixs, isn't it? what does the second line mean? It seems the second line is always 0? 
Thank you!

**Comment by tomviering** [comment]
Hey, I have a similar question to xiangchong1. When I download the aligned Modelnet40 (manual or automatic), I find there is a single 2 GB file in the tar-file. In what format is it stored and how do you get the .off files out? Any help would be appreciated!

**Comment by NimSed** [comment]
@xiangchong1 
.off files are the already aligned objects. So you basically do not need the .annot files at all. 
The info in the annot files shows the rotation applied on the original .off models to get them aligned: first line is the rotation around z axis (azimuth), and second line is the elevation (usually zero).

**Comment by NimSed** [comment]
@TommieV 
Would you please open a new issue for your question? (to keep the answers clean for the others)

**Comment by xiangchong1** [comment]
@NimSed Thank you! That is very helpful

**Comment by xiangchong1** [comment]
@TommieV http://segeval.cs.princeton.edu/public/off_format.html 
see this link. it should help
